#!/usr/bin/env sh
# adbtool uninstall-user -u 0 -f harmonyos2-4

#android
#android.ext.services
#androidhwext
#com.android.apps.tag
#com.android.backupconfirm
#com.android.bluetooth
#com.android.bluetoothmidiservice
#com.android.calendar
#com.android.calllogbackup
#com.android.captiveportallogin
#com.android.carrierconfig
#com.android.cellbroadcastreceiver
#com.android.certinstaller
#com.android.companiondevicemanager
#com.android.contacts
#com.android.cts.ctsshim
#com.android.cts.priv.ctsshim
#com.android.deskclock
#com.android.documentsui
#com.android.dreams.phototable
#com.android.emergency
#com.android.externalstorage
#com.android.frameworkres.overlay
#com.android.gallery3d
#com.android.htmlviewer
#com.android.incallui
#com.android.inputdevices
#com.android.internal.systemui.navbar.gestural
#com.android.keychain
#com.android.location.fused
#com.android.managedprovisioning
com.android.mediacenter
#com.android.mms
#com.android.mms.service
#com.android.modulemetadata
#com.android.mtp
#com.android.networkstack.inprocess
#com.android.networkstack.permissionconfig
#com.android.nfc
#com.android.ons
#com.android.packageinstaller
#com.android.pacprocessor
#com.android.permissioncontroller
#com.android.phone
#com.android.printspooler
#com.android.providers.blockednumber
#com.android.providers.calendar
#com.android.providers.contacts
#com.android.providers.downloads
#com.android.providers.downloads.ui
#com.android.providers.media
#com.android.providers.settings
#com.android.providers.telephony
#com.android.providers.userdictionary
#com.android.proxyhandler
#com.android.se
#com.android.server.telecom
#com.android.settings
#com.android.sharedstoragebackup
#com.android.shell
#com.android.statementservice
#com.android.stk
#com.android.systemui
#com.android.systemui.overlay
#com.android.vending
#com.android.vpndialogs
#com.android.wallpaper.livepicker
#com.android.wallpaperbackup
#com.android.wallpapercropper

# 百度输入法华为版
com.baidu.input_huawei

# ConfigUpdater
#com.google.android.configupdater

# Android Shared Library
#com.google.android.ext.shared

# Google Play 服务
#com.google.android.gms

# Google 服务框架
#com.google.android.gsf

# Android Accessibility Suite
#com.google.android.marvin.talkback

# Google One Time Init
#com.google.android.onetimeinitializer

# @
#com.google.android.overlay.gmsconfig

# @
#com.google.android.overlay.settingsProvider

# Google Partner Setup
#com.google.android.partnersetup

# Print Service Recommendation Service
#com.google.android.printservice.recommendation

# Android System WebView
#com.google.android.webview

# ARCore
#com.google.ar.core

# AirLink
com.huawei.airlink

# 无线投屏
com.huawei.android.airsharing

# HwChrService
com.huawei.android.chr

# 查找设备
com.huawei.android.findmyphone

# 悬浮导航
#com.huawei.android.FloatTasks

# HMS 服务框架
#com.huawei.android.hsf

# HwAps
#com.huawei.android.hwaps

# 软件更新
#com.huawei.android.hwouc

# 升级向导
com.huawei.android.hwupgradeguide

# HwInstantOnline
com.huawei.android.instantonline

# 华为分享
com.huawei.android.instantshare

# Share
#com.huawei.android.internal.app

# K 歌特效
com.huawei.android.karaoke

# 华为桌面
#com.huawei.android.launcher

# 工程菜单(*#*#2846579#*#*)
#com.huawei.android.projectmenu

# 推送服务
#com.huawei.android.pushagent

# 主题
#com.huawei.android.thememanager

# WLAN 直连
com.huawei.android.wfdft

# @
#com.huawei.androidx

# 华为应用市场
com.huawei.appmarket

# AREngineServer
com.huawei.arengine.service

# 关键资产同步
com.huawei.assetsync

# 关键资产同步管理服务
com.huawei.assetsyncservice

# 音频产品管家
com.huawei.audioaccessorymanager

# BehaviorAuth
com.huawei.behaviorauth

# 通过蓝牙导入
#com.huawei.bluetooth

# 骨声纹识别
#com.huawei.bonevoiceui

# 浏览器
com.huawei.browser

# CA
#com.huawei.ca

# 相机
#com.huawei.camera

# HwCameraKit
#com.huawei.camerakit.impl

# HwCoAuthService
#com.huawei.coauthservice

# 联系人同步
com.huawei.contacts.sync

# 取词(智能识屏插件)
com.huawei.contentsensor

# 智慧协同
com.huawei.controlcenter

# DEF
#com.huawei.def

# 我的文件
com.huawei.desktop.explorer

# 系统界面
#com.huawei.desktop.systemui

# TrustedDeviceAuth
#com.huawei.deviceauth

# HwGroupManager
#com.huawei.devicegroupmanage

# 分布式设备管理
#com.huawei.devicemanager

# HwDistributedKeyManager
#com.huawei.distributed.kms

# 分布式设备管理
#com.huawei.dmsdp

# SIM 卡管理
#com.huawei.dsdscardmanager

# HwEasyGo
com.huawei.easygo

# 快应用中心
com.huawei.fastapp

# FeatureFramework
#com.huawei.featurelayer.featureframework

# 地图服务
#com.huawei.featurelayer.sharedfeature.map

# FIDO UAF Client
#com.huawei.fido.uafclient

# 文件管理
com.huawei.filemanager

# foundation
#com.huawei.harmonyos.foundation

# ffmpeg
#com.huawei.hff

# HiAI Base
com.huawei.hiaction

# 华为智慧引擎
com.huawei.hiai

# Huawei HiCar
com.huawei.hicar

# HiCard
com.huawei.hicard

# 云空间服务
com.huawei.hicloud

# 云空间
com.huawei.hidisk

# 智慧生活基础服务
com.huawei.hilink.framework

# 华为视频
com.huawei.himovie

# HiMoviePlayerPlus
com.huawei.himovie.partner1

# HiMoviePlayerPlus
com.huawei.himovie.partner2

# 智慧识屏
com.huawei.hitouch

# hiview
#com.huawei.hiview

# HiViewTunnel
#com.huawei.hiviewtunnel

# OTA Engine
#com.huawei.hms.dupdateengine

# FIDO UAF ASM
#com.huawei.hwasm

# HwBlockChain(区块链)
com.huawei.hwblockchain

# HwDDMP
#com.huawei.hwddmp

# 智能检测
com.huawei.hwdetectrepair

# HwDiagnosis
com.huawei.hwdiagnosis

# 智慧多窗
#com.huawei.hwdockbar

# HMS Core
#com.huawei.hwid

# 滚动截屏
#com.huawei.HwMultiScreenShot

# HwPanPayService
#com.huawei.hwpanpayservice

# HwStartupGuide
#com.huawei.hwstartupguide

# 畅连服务
com.huawei.hwvoipservice

# iAware
#com.huawei.iaware

# 设备连接服务
#com.huawei.iconnect

# 杜比全景声
#com.huawei.imedia.dolby

# Histen
#com.huawei.imedia.sws

# HwImsService
#com.huawei.ims

# 智慧助手·今天
com.huawei.intelligent

# 下载语言
#com.huawei.languagedownloader

# 位置服务
#com.huawei.lbs

# 华山
#com.huawei.livewallpaper.matetwenty

# 杂志锁屏
com.huawei.magazine

# 媒体播控中心
#com.huawei.mediacontroller

# MMITest
#com.huawei.mmitest

# 手势服务
#com.huawei.motionservice

# 综合传感信息处理平台
com.huawei.msdp

# HwAudioKit
#com.huawei.multimedia.audioengine

# hivideoplayengine
#com.huawei.multimedia.hivideoplayengine

# 数据管理服务
#com.huawei.nb.service

# HwNearby
#com.huawei.nearby

# 号码识别
#com.huawei.numberidentity

# 相机
#com.huawei.ohos.camera

# 服务中心
com.huawei.ohos.famanager

# HiWindow
#com.huawei.ohos.hiwindow

# 图库
#com.huawei.ohos.photos

# 全局搜索数据服务
com.huawei.ohos.search

# 小艺建议
com.huawei.ohos.suggestion

# OneHopSvcClient
#com.huawei.onehopsvcclient

# OneHopSvcHost
#com.huawei.onehopsvchost

# 健康使用手机(无法 uninstall + disable)
com.huawei.parentcontrol

# 华为分享
com.huawei.pcassistant

# 华为智能建议
com.huawei.pengine

# 通话录音
#com.huawei.phone.recorder

# 我的华为
com.huawei.phoneservice

# HAware
#com.huawei.powergenie

# 华为打印
#com.huawei.printservice

# 隐私空间
#com.huawei.privatespace

# Profile Services
com.huawei.profile

# 华为 RCS 服务(5G 消息/增强信息)
com.huawei.rcsserviceapplication

# HwHiAIDSEngine
com.huawei.recsys

# RegService
#com.huawei.regservice

# RemotePassword
com.huawei.remotepassword

# 智慧视觉
com.huawei.scanner

# 屏幕录制
#com.huawei.screenrecorder

# 智慧搜索
com.huawei.search

# 融合搜索服务
com.huawei.searchservice

# Secure IME(安全键盘)
#com.huawei.secime

# 安全组件
#com.huawei.securitymgr

# HwSecurityPluginBase
#com.huawei.securitypluginbase

# 华为安全公共服务
#com.huawei.securityserver

# 天际通数据服务
com.huawei.skytone

# 智能截屏
#com.huawei.smartshot

# 地理围栏服务
#com.huawei.spaceservice

# 情景智能
com.huawei.suggestion

# HwSynergy
com.huawei.synergy

# 手机管家
#com.huawei.systemmanager

# 系统服务
#com.huawei.systemserver

# 智能解锁
#com.huawei.trustagent

# 设备认证服务
#com.huawei.trustcircle

# HwTrustedThingsAuth
#com.huawei.trustedthingsauth

# 支付保护中心
com.huawei.trustspace

# 智慧语音
com.huawei.vassistant

# 华为钱包
com.huawei.wallet

# WalletSDK
com.huawei.wallet.sdk.walletsdk

# waudio
com.huawei.waudio

# Huawei WebView
#com.huawei.webview

# HwWifiproBqeService
#com.huawei.wifiprobqeservice

# 讯飞语音引擎
com.iflytek.speechsuite

# HiMoviePlayerPlus(华为视频-搜狐视频模块)
com.sohu.sohuvideo.emplayer

# HiMoviePlayerPlus(华为视频-腾讯视频模块)
com.tencent.qqlivehuawei

# MediaLibrary(鸿蒙媒体库)
#ohos.media.medialibrary


# huawei mate 40 harmonyos 4.2.0.180

#android.ext.shared
#com.android.cellbroadcastservice
#com.android.connectivity.resources
#com.android.hotspot2.osulogin
#com.android.networkstack.tethering.inprocess
#com.android.printservice.recommendation
#com.android.providers.media.module
#com.android.wifi.resources
#com.android.wifi.resources.overlay

# 屏幕朗读
com.bjbyhd.screenreader_huawei

# AutoRegSms
#com.huawei.android.AutoRegSms

# UEInfoCheck
#com.huawei.android.UEInfoCheck

# 熄屏显示
#com.huawei.aod

# 日历
#com.huawei.calendar

# 联系人
#com.huawei.contacts

# 时钟
#com.huawei.deskclock

# 中转站
#com.huawei.distributedpasteboard

# 华为手写笔服务
#com.huawei.featurelayer.sharedfeature.stylus

# 应用助手
com.huawei.gameassistant

# Gateway
#com.huawei.gateway

# 智能信息
com.huawei.hbm

# 视频播放器
com.huawei.himovie.local

# @
#com.huawei.hwbluetoothpencilmanager

# 文件预览
#com.huawei.hwpreview

# iConnectUI
#com.huawei.iconnect.ui

# 超级壁纸
#com.huawei.livewallpaper.paradise

# 润泽
#com.huawei.livewallpaper.ripplestone

# 华为音乐
com.huawei.music

# 音乐播放器
com.huawei.music.local

# 华为家庭存储同步服务
com.huawei.nemo

# CollaborationCenter
#com.huawei.ohos.collaborationcenter

# 小艺输入法
com.huawei.ohos.inputmethod

# 安全隐私中心服务卡片
com.huawei.ohos.security.privacycenter

# 图库
#com.huawei.photos

# HSDR
#com.huawei.security.hsdr

# 安全隐私中心(关闭纯净模式需要卸载, 卸载后应用-权限管理无法进入)
# 第一条指令提示无权限, 只能在 app 中设置才会有权限
# adb shell settings put secure pure_mode_state 1
# adb shell settings put secure pure_enhanced_mode_state 1
# adb shell settings put global app_check_risk 0
com.huawei.security.privacycenter

# 手写笔悬浮窗
#com.huawei.stylus.floatmenu

# 钱包服务卡片
com.huawei.wallet.facard
