#!/usr/bin/env sh
# adbtool uninstall-user -u 0 -f xiaomi_15_ultra_hyperos2

#android
#android.aosp.overlay
#android.aosp.overlay.telephony
#android.auto_generated_characteristics_rro
#android.miui.home.launcher.res
#android.miui.overlay
#android.miui.overlay.telephony
#android.overlay.common
#android.overlay.target
#android.qvaoverlay.common
#com.android.adservices.api
#com.android.apps.tag
#com.android.appsearch.apk
#com.android.avatarpicker
#com.android.backupconfirm
#com.android.bips
#com.android.bluetooth
#com.android.bluetooth.overlay
#com.android.bluetoothmidiservice
# 浏览器
com.android.browser
#com.android.calendar
#com.android.calllogbackup
#com.android.camera
#com.android.cameraextensions
#com.android.captiveportallogin
#com.android.carrierconfig
#com.android.carrierconfig.overlay.common
#com.android.carrierconfig.overlay.miui
#com.android.carrierdefaultapp
#com.android.cellbroadcastreceiver
#com.android.cellbroadcastreceiver.module
#com.android.cellbroadcastreceiver.overlay.common
#com.android.cellbroadcastservice
#com.android.certinstaller
#com.android.companiondevicemanager
#com.android.companiondevicemanager.auto_generated_characteristics_rro
#com.android.compos.payload
#com.android.connectivity.resources
#com.android.contacts
#com.android.credentialmanager
#com.android.cts.ctsshim
#com.android.cts.priv.ctsshim
#com.android.DeviceAsWebcam
#com.android.devicediagnostics
#com.android.devicelockcontroller
#com.android.dreams.basic
#com.android.dynsystem
#com.android.egg
# 电子邮件
com.android.email
#com.android.emergency
#com.android.externalstorage
#com.android.federatedcompute.services
# 文件管理
com.android.fileexplorer
#com.android.health.connect.backuprestore
#com.android.healthconnect.controller
#com.android.hotspot2.osulogin
#com.android.htmlviewer
#com.android.imsserviceentitlement
#com.android.incallui
#com.android.inputdevices
#com.android.inputsettings.overlay.miui
#com.android.intentresolver
#com.android.internal.display.cutout.emulation.corner
#com.android.internal.display.cutout.emulation.double
#com.android.internal.display.cutout.emulation.hole
#com.android.internal.display.cutout.emulation.tall
#com.android.internal.display.cutout.emulation.waterfall
#com.android.internal.systemui.navbar.gestural
#com.android.internal.systemui.navbar.threebutton
#com.android.internal.systemui.navbar.transparent
#com.android.keychain
#com.android.localtransport
#com.android.location.fused
#com.android.managedprovisioning
#com.android.managedprovisioning.overlay
#com.android.microdroid.empty_payload
#com.android.mms
#com.android.mms.service
#com.android.modulemetadata
#com.android.mtp
#com.android.musicfx
#com.android.networkstack
#com.android.networkstack.overlay.miui
#com.android.networkstack.tethering
#com.android.nfc
#com.android.ondevicepersonalization.services
#com.android.ons
#com.android.overlay.cngmstelecomm
#com.android.overlay.gmscontactprovider
#com.android.overlay.gmssettingprovider
#com.android.overlay.gmssettings
#com.android.overlay.gmstelecomm
#com.android.overlay.gmstelephony
#com.android.overlay.systemui
#com.android.pacprocessor
#com.android.permissioncontroller
#com.android.phone
#com.android.phone.auto_generated_characteristics_rro
#com.android.phone.overlay.common
#com.android.phone.overlay.miui
#com.android.printspooler
#com.android.providers.blockednumber
#com.android.providers.calendar
#com.android.providers.contactkeys
#com.android.providers.contacts
# 下载管理
com.android.providers.downloads
#com.android.providers.downloads.ui
#com.android.providers.media
#com.android.providers.media.module
#com.android.providers.partnerbookmarks
#com.android.providers.settings
#com.android.providers.settings.overlay
#com.android.providers.telephony
#com.android.providers.telephony.auto_generated_characteristics_rro
#com.android.providers.telephony.overlay.miui
#com.android.providers.userdictionary
#com.android.provision
#com.android.proxyhandler
# 搜索
com.android.quicksearchbox
#com.android.rkpdapp
#com.android.role.notes.enabled
#com.android.safetycenter.resources
#com.android.sdksandbox
#com.android.se
#com.android.se.overlay.target
#com.android.server.deviceconfig.resources
#com.android.server.telecom
#com.android.server.telecom.overlay.common
#com.android.server.telecom.overlay.miui
#com.android.settings
#com.android.settings.intelligence
#com.android.settings.overlay.common
#com.android.settings.overlay.miui
#com.android.sharedstoragebackup
#com.android.shell
#com.android.simappdialog
#com.android.smspush
#com.android.soundrecorder
#com.android.statementservice
#com.android.stk
#com.android.stk.overlay.miui
#com.android.storagemanager
#com.android.systemui
#com.android.systemui.accessibility.accessibilitymenu
#com.android.systemui.gesture.line.overlay
#com.android.systemui.navigation.bar.overlay
#com.android.systemui.overlay.common
#com.android.systemui.overlay.miui
#com.android.theme.font.notoserifsource
# 主题壁纸
#com.android.thememanager
#com.android.thememanager.customthemeconfig.config.overlay
#com.android.traceur
# 系统更新
com.android.updater
#com.android.uwb.resources
#com.android.uwb.resources.overlay.common
#com.android.vending
#com.android.virtualmachine.res
#com.android.vpndialogs
#com.android.wallpaper.livepicker
#com.android.wallpaperbackup
#com.android.wallpapercropper
#com.android.wifi.dialog
#com.android.wifi.resources
#com.android.wifi.resources.overlay.common
#com.android.wifi.resources.overlay.target
#com.android.wifi.resources.xiaomi

# CatchLog
#com.bsp.catchlog

# 多看
com.duokan.reader

# MI FIDO
#com.fido.asm

# In-Display Fingerprint
#com.goodix.fingerprint.producttest

# 开关控制
#com.google.android.accessibility.switchaccess

# 
#com.google.android.cellbroadcastreceiver.overlay.miui

# 
#com.google.android.cellbroadcastservice.overlay.miui

# ConfigUpdater
#com.google.android.configupdater

# 文件
#com.google.android.documentsui

# Android Services Library
#com.google.android.ext.services

# Android Shared Library
#com.google.android.ext.shared

# Google Play 服务
#com.google.android.gms

# Google 位置记录
#com.google.android.gms.location.history

# Google 服务框架
#com.google.android.gsf

# Android 无障碍套件
#com.google.android.marvin.talkback

# Google One Time Init
#com.google.android.onetimeinitializer

# 
#com.google.android.overlay.gmsconfig

# 
#com.google.android.overlay.modules.ext.services.cn

# Print Service Recommendation Service
#com.google.android.printservice.recommendation

# Android System WebView
#com.google.android.webview

# 
#com.google.android.wifi.resources.overlay.common

# 
#com.google.android.wifi.resources.overlay.target

# 
#com.google.android.wifi.resources.xiaomi

# 权限管理服务
#com.lbe.security.miui

# 小米画报
com.mfashiongallery.emag

# 互联互通服务
com.milink.service

# 小米闻声
#com.miui.accessibility

# Analytics
com.miui.analytics

# 息屏与锁屏编辑
#com.miui.aod

# 应用通话录音
#com.miui.audiomonitor

# 备份
#com.miui.backup

# 用户反馈
#com.miui.bugreport

# 计算器
#com.miui.calculator

# CarWith
com.miui.carlink

# CIT
#com.miui.cit

# 垃圾清理
com.miui.cleanmaster

# 小米云备份
com.miui.cloudbackup

# 小米云服务
com.miui.cloudservice

# 指南针
#com.miui.compass

# 应用程序扩展服务
#com.miui.contentcatcher

# 传送门
com.miui.contentextension

# System SDK
#com.miui.core

# 
#com.miui.core.internal.services

# 系统质量服务
com.miui.daemon

# Bokeh
#com.miui.extraphoto

# 相册
#com.miui.gallery

# 家人守护
com.miui.greenguard

# 系统安全组件
com.miui.guardprovider

# 系统桌面
#com.miui.home

# 快应用服务框架
com.miui.hybrid

# 媒体查看器
#com.miui.mediaviewer

# MiCloudSync
com.miui.micloudsync

# 小米互传
com.miui.mishare.connectivity

# 系统质量监测
com.miui.misightservice

# 音质音效
#com.miui.misound

# 壁纸
#com.miui.miwallpaper

# 
#com.miui.miwallpaper.config.overlay

# 
#com.miui.miwallpaper.overlay.customize

# 内容中心
com.miui.newhome

# 小米智能卡网页组件
com.miui.nextpay

# 笔记
com.miui.notes

# 通知管理
#com.miui.notification

# 应用包管理组件
#com.miui.packageinstaller

# 智能助理(负一屏)
com.miui.personalassistant

# 剪贴板与常用语
#com.miui.phrase

# 电量和性能
#com.miui.powerkeeper

# 
#com.miui.qr

# 
#com.miui.rom

# 屏幕录制
#com.miui.screenrecorder

# 截屏
#com.miui.screenshot

# 系统服务组件
#com.miui.securityadd

# 安全服务
#com.miui.securitycenter

# 
#com.miui.securitycenter.securitycenter_phone_overlay.config.overlay

# 系统功能组件
#com.miui.securitycore

# 小米安全键盘
#com.miui.securityinputmethod

# 手机管家
com.miui.securitymanager

# 
#com.miui.settings.rro.device.config.overlay
#com.miui.settings.rro.device.hide.statusbar.overlay
#com.miui.settings.rro.device.systemui.overlay
#com.miui.settings.rro.device.type.overlay

# 系统
#com.miui.system

# 遮罩
#com.miui.system.overlay

# 智能服务
com.miui.systemAdSolution

# 遮罩
#com.miui.systemui.carriers.overlay

# 遮罩
#com.miui.systemui.devices.overlay

# DevicesAndroidOverlay
#com.miui.systemui.overlay.devices.android

# 三方应用异常分析
com.miui.thirdappassistant

# 悬浮球
#com.miui.touchassistant

# 小米智能卡
com.miui.tsmclient

# UI信息工具
#com.miui.uireporter

# 小米视频
com.miui.video

# 全球上网
com.miui.virtualsim

# 超级小爱
com.miui.voiceassist

# 超级小爱 遮罩
com.miui.voiceassistoverlay

# 语音唤醒
com.miui.voicetrigger

# MConnService
#com.miui.vsimcore

# 
#com.miui.wallpaper.overlay.customize

# 天气
com.miui.weather2

# WMService(无线管理服务)
#com.miui.wmsvc

# 生活黄页
#com.miui.yellowpage

# textaction
#com.miuix.editor

# SystemHelper
#com.mobiletools.systemhelper

# 新通话
#com.newcall

# 
#com.newcall.overlay.miui

# novavis
#com.novatek.novavis

#com.qti.dcf
#com.qti.dpmserviceapp
#com.qti.phone
#com.qti.qcc
#com.qti.qualcomm.datastatusnotification
#com.qti.qualcomm.deviceinfo
#com.qti.service.colorservice
#com.qualcomm.atfwd
#com.qualcomm.atfwd2
#com.qualcomm.location
#com.qualcomm.qcrilmsgtunnel
#com.qualcomm.qti.biometrics.fingerprint.qfsfactorytest
#com.qualcomm.qti.callfeaturessetting
#com.qualcomm.qti.cne
#com.qualcomm.qti.confdialer
#com.qualcomm.qti.devicestatisticsservice
#com.qualcomm.qti.dynamicddsservice
#com.qualcomm.qti.gpudrivers.sun.api35
#com.qualcomm.qti.ims
#com.qualcomm.qti.poweroffalarm
#com.qualcomm.qti.qcolor
#com.qualcomm.qti.qms.service.connectionsecurity
#com.qualcomm.qti.qms.service.trustzoneaccess
#com.qualcomm.qti.remoteSimlockAuth
#com.qualcomm.qti.ridemodeaudio
#com.qualcomm.qti.server.qtiwifi
#com.qualcomm.qti.server.wigig.tethering.rro
#com.qualcomm.qti.services.systemhelper
#com.qualcomm.qti.simcontacts
#com.qualcomm.qti.telephonyservice
#com.qualcomm.qti.uceShimService
#com.qualcomm.qti.uim
#com.qualcomm.qti.uimGbaApp
#com.qualcomm.qti.workloadclassifier
#com.qualcomm.qti.xrcb
#com.qualcomm.qti.xrvd.service
#com.qualcomm.timeservice
#com.qualcomm.uimremoteclient
#com.qualcomm.uimremoteserver
#com.qualcomm.wfd.service

# EidService
#com.rongcard.eid

# 搜狗输入法小米版(安装新输入法以后再进行卸载)
com.sohu.inputmethod.sogou.xiaomi

# 腾讯 Soter 服务(微信支付生物认证相关)
#com.tencent.soter.soterserver

# 银联可信服务安全组件小米版本
com.unionpay.tsmservice.mi

# WAPI证书
#com.wapi.wapicertmanage

# 售后支持
com.xiaomi.ab

# 小米账号
com.xiaomi.account

# AI通话
com.xiaomi.aiasst.service

# 翻译
com.xiaomi.aiasst.vision

# 小米澎湃AI引擎
com.xiaomi.aicr

# XiaoaiRecommendation
com.xiaomi.aireco

# 
com.xiaomi.aon

# 弹幕通知
#com.xiaomi.barrage

# bdsms_service
#com.xiaomi.bdsms

# Bluetooth Extension
#com.xiaomi.bluetooth

# 
#com.xiaomi.bluetooth.rro.device.config.overlay

# CameraMind
#com.xiaomi.cameramind

# 相机标定
#com.xiaomi.cameratools

# 小米数字钥匙框架
#com.xiaomi.digitalkey

# 查找设备
#com.xiaomi.finddevice

# 游戏中心
com.xiaomi.gamecenter

# 游戏服务
com.xiaomi.gamecenter.sdk.service

# Polaris
#com.xiaomi.gnss.polaris

# Joyose
#com.xiaomi.joyose

# 融合位置服务
#com.xiaomi.location.fused

# 自动连招
com.xiaomi.macro

# 应用商店
com.xiaomi.market

# 网络位置服务
#com.xiaomi.metoknlp

# 小米互联通信服务
com.xiaomi.mi_connect_service

# 
#com.xiaomi.micloud.sdk

# 跨屏协同服务
com.xiaomi.mirror

# 小米汽车互联服务
com.xiaomi.mis

# 小米设置
#com.xiaomi.misettings

# 鲁班(MTB)
#com.xiaomi.mtb

# otrpbroker
#com.xiaomi.otrpbroker

# 米币支付
com.xiaomi.payment

# HyperPhone
#com.xiaomi.phone

# 
#com.xiaomi.phone.overlay

# 运营商服务
#com.xiaomi.registration

# AI扫描
com.xiaomi.scanner

# SecurityOnetrackService
#com.xiaomi.security.onetrack

# 小米SIM卡激活服务
com.xiaomi.simactivate.service

# touchservice
#com.xiaomi.touchservice

# MiTrustService
#com.xiaomi.trustservice

# GPU 驱动更新
#com.xiaomi.ugd

# 小米服务框架
#com.xiaomi.xmsf

# Xiaomi Service Framework Keeper
#com.xiaomi.xmsfkeeper

# 系统界面组件
#miui.systemui.plugin

# 
#org.codeaurora.ims

# IfaaService(支付宝生物认证相关)
#org.ifaa.aidl.manager

#vendor.qti.bluetooth.xpan
#vendor.qti.bluetooth.xpan.overlay.target
#vendor.qti.data.txpwradmin
#vendor.qti.hardware.cacert.server
#vendor.qti.imsdatachannel
#vendor.qti.imsrcs
#vendor.qti.iwlan
#vendor.qti.qesdk.sysservice
