#!/usr/bin/env sh
# adbtool uninstall-user -u 0 -f xiaomi_15_ultra_hyperos2_eu

#android
#android.aosp.overlay
#android.aosp.overlay.telephony
#android.auto_generated_characteristics_rro
#android.miui.overlay
#android.miui.overlay.telephony
#android.overlay.common
#android.overlay.target
#android.qvaoverlay.common
# 小米文档查看器（WPS定制）
#cn.wps.moffice_eng.xiaomi.lite
#com.android.adservices.api
#com.android.apps.tag
#com.android.appsearch.apk
#com.android.avatarpicker
#com.android.backupconfirm
#com.android.bips
#com.android.bluetooth
#com.android.bluetooth.overlay
#com.android.bluetoothmidiservice
#com.android.calendar
#com.android.calllogbackup
#com.android.camera
#com.android.cameraextensions
#com.android.captiveportallogin
#com.android.carrierconfig
#com.android.carrierconfig.overlay.common
#com.android.carrierconfig.overlay.miui
#com.android.carrierdefaultapp
#com.android.cellbroadcastreceiver
#com.android.cellbroadcastreceiver.module
#com.android.cellbroadcastreceiver.overlay.common
#com.android.cellbroadcastservice
#com.android.certinstaller
#com.android.companiondevicemanager
#com.android.companiondevicemanager.auto_generated_characteristics_rro
#com.android.compos.payload
#com.android.connectivity.resources
#com.android.contacts
#com.android.credentialmanager
#com.android.cts.ctsshim
#com.android.cts.priv.ctsshim
#com.android.deskclock
#com.android.DeviceAsWebcam
#com.android.devicediagnostics
#com.android.devicelockcontroller
#com.android.dynsystem
#com.android.egg
# 电子邮件
com.android.email
#com.android.emergency
#com.android.externalstorage
#com.android.federatedcompute.services
#com.android.fileexplorer
#com.android.health.connect.backuprestore
#com.android.healthconnect.controller
#com.android.hotspot2.osulogin
#com.android.hotwordenrollment.okgoogle
#com.android.hotwordenrollment.xgoogle
#com.android.htmlviewer
#com.android.imsserviceentitlement
#com.android.incallui
#com.android.inputdevices
#com.android.inputsettings.overlay.miui
#com.android.intentresolver
#com.android.internal.display.cutout.emulation.corner
#com.android.internal.display.cutout.emulation.double
#com.android.internal.display.cutout.emulation.hole
#com.android.internal.display.cutout.emulation.tall
#com.android.internal.display.cutout.emulation.waterfall
#com.android.internal.systemui.navbar.gestural
#com.android.internal.systemui.navbar.threebutton
#com.android.internal.systemui.navbar.transparent
#com.android.keychain
#com.android.localtransport
#com.android.location.fused
#com.android.managedprovisioning
#com.android.microdroid.empty_payload
#com.android.mms
#com.android.mms.service
#com.android.mtp
#com.android.musicfx
#com.android.networkstack
#com.android.networkstack.tethering
#com.android.nfc
#com.android.ondevicepersonalization.services
#com.android.ons
#com.android.overlay.circletosearch
#com.android.overlay.gmscontactprovider
#com.android.overlay.gmssettingprovider
#com.android.pacprocessor
#com.android.permissioncontroller
#com.android.phone
#com.android.phone.auto_generated_characteristics_rro
#com.android.phone.overlay.common
#com.android.phone.overlay.miui
#com.android.printspooler
#com.android.providers.blockednumber
#com.android.providers.calendar
#com.android.providers.contactkeys
#com.android.providers.contacts
#com.android.providers.downloads
#com.android.providers.downloads.ui
#com.android.providers.media
#com.android.providers.media.module
#com.android.providers.settings
#com.android.providers.settings.overlay
#com.android.providers.telephony
#com.android.providers.telephony.auto_generated_characteristics_rro
#com.android.providers.telephony.overlay.miui
#com.android.providers.userdictionary
#com.android.provision
#com.android.proxyhandler
#com.android.rkpdapp
#com.android.role.notes.enabled
#com.android.safetycenter.resources
#com.android.sdksandbox
#com.android.se
#com.android.se.overlay.target
#com.android.server.deviceconfig.resources
#com.android.server.telecom
#com.android.server.telecom.overlay.common
#com.android.server.telecom.overlay.miui
#com.android.settings
#com.android.settings.intelligence
#com.android.settings.overlay.common
#com.android.settings.overlay.miui
#com.android.sharedstoragebackup
#com.android.shell
#com.android.simappdialog
#com.android.smspush
#com.android.soundrecorder
#com.android.statementservice
#com.android.stk
#com.android.stk.overlay.miui
#com.android.storagemanager
#com.android.systemui
#com.android.systemui.accessibility.accessibilitymenu
#com.android.systemui.gesture.line.overlay
#com.android.systemui.navigation.bar.overlay
#com.android.systemui.overlay.common
#com.android.systemui.overlay.miui
#com.android.theme.font.notoserifsource
#com.android.thememanager
#com.android.traceur
# 系统更新
#com.android.updater
#com.android.uwb.resources
#com.android.uwb.resources.overlay.common
# Google Play 商店
com.android.vending
#com.android.virtualmachine.res
#com.android.vpndialogs
#com.android.wallpaper.livepicker
#com.android.wallpaperbackup
#com.android.wallpapercropper
#com.android.wifi.dialog
#com.android.wifi.resources
#com.android.wifi.resources.overlay.common
#com.android.wifi.resources.overlay.target
#com.android.wifi.resources.xiaomi
#com.bsp.catchlog
#com.fido.asm

#com.goodix.fingerprint.producttest
# Android Switch
#com.google.android.apps.restore
# ConfigUpdater
#com.google.android.configupdater
# 文件
#com.google.android.documentsui
#com.google.android.ext.services
#com.google.android.ext.shared
# 应用商店反馈代理程序
#com.google.android.feedback
# Google Play 服务
com.google.android.gms
# Google 位置记录
#com.google.android.gms.location.history
# 系统 - 家长控制
#com.google.android.gms.supervision
# Google 快速搜索框
com.google.android.googlequicksearchbox
# Google 服务框架
com.google.android.gsf
# Gboard 输入法
#com.google.android.inputmethod.latin
# Android 无障碍套件
#com.google.android.marvin.talkback
#com.google.android.modulemetadata
# Google One Time Init
#com.google.android.onetimeinitializer
#com.google.android.overlay.gmsconfig.common
#com.google.android.overlay.gmsconfig.geotz
#com.google.android.overlay.gmsconfig.gsa
#com.google.android.overlay.modules.documentsui
#com.google.android.overlay.modules.ext.services
#com.google.android.overlay.modules.modulemetadata.forframework
# Google Partner Setup
#com.google.android.partnersetup
#com.google.android.printservice.recommendation
# Android Auto
#com.google.android.projection.gearhead
# Android 设置向导
#com.google.android.setupwizard
# 音效
#com.google.android.soundpicker
# Google 日历同步
#com.google.android.syncadapters.calendar
# Google 通讯录同步
#com.google.android.syncadapters.contacts
# Google 语音识别和语音合成
#com.google.android.tts
#com.google.android.webview
#com.google.android.wifi.resources.overlay.common
#com.google.android.wifi.resources.overlay.target
#com.google.android.wifi.resources.xiaomi

#com.lbe.security.miui
# 小米画报
com.mfashiongallery.emag
#com.mi.appfinder
# 浏览器
com.mi.globalbrowser
# 健康
com.mi.health
# 连接至 Windows
com.microsoft.appmanager
# Device Integration Service
com.microsoft.deviceintegrationservice
# Cross Device Broker
com.microsoftsdk.crossdeviceservicebroker
#com.milink.service
#com.miui.accessibility
#com.miui.aod
#com.miui.audiomonitor
#com.miui.backup
#com.miui.bugreport
#com.miui.calculator
#com.miui.cit
#com.miui.cleaner
# 小米云备份
com.miui.cloudbackup
# 小米云服务
com.miui.cloudservice
#com.miui.compass
#com.miui.contentcatcher
#com.miui.core
#com.miui.core.internal.services
#com.miui.daemon
#com.miui.euicc
#com.miui.extraphoto
#com.miui.gallery
# 系统安全组件
#com.miui.guardprovider
#com.miui.home
# 小米换机
com.miui.huanji
#com.miui.mediaeditor
# MiCloudSync
com.miui.micloudsync
# 服务与反馈
com.miui.miservice
#com.miui.mishare.connectivity
#com.miui.misightservice
#com.miui.misound
#com.miui.miwallpaper
#com.miui.miwallpaper.config.overlay
#com.miui.miwallpaper.overlay.customize
# 小米云盘
com.miui.newmidrive
# 笔记
com.miui.notes
#com.miui.notification
#com.miui.packageinstaller
#com.miui.personalassistant
#com.miui.phrase
# 音乐
com.miui.player
#com.miui.powerkeeper
#com.miui.qr
#com.miui.rom
#com.miui.screenrecorder
#com.miui.screenshot
#com.miui.securityadd
#com.miui.securitycenter
#com.miui.securitycore
#com.miui.settings.rro.device.config.overlay
#com.miui.settings.rro.device.hide.statusbar.overlay
#com.miui.settings.rro.device.systemui.overlay
#com.miui.settings.rro.device.type.overlay
#com.miui.system
#com.miui.system.overlay
#com.miui.systemui.carriers.overlay
#com.miui.systemui.devices.overlay
#com.miui.systemui.overlay.devices.android
#com.miui.touchassistant
# 小米视频
com.miui.videoplayer
#com.miui.vsimcore
#com.miui.wallpaper.overlay.customize
# 天气
com.miui.weather2
#com.miuix.editor
#com.novatek.novavis

#com.qti.dcf
#com.qti.dpmserviceapp
#com.qti.phone
#com.qti.qcc
#com.qti.qualcomm.datastatusnotification
#com.qti.qualcomm.deviceinfo
#com.qti.service.colorservice
#com.qualcomm.atfwd
#com.qualcomm.atfwd2
#com.qualcomm.location
#com.qualcomm.qcrilmsgtunnel
#com.qualcomm.qti.biometrics.fingerprint.qfsfactorytest
#com.qualcomm.qti.callfeaturessetting
#com.qualcomm.qti.cne
#com.qualcomm.qti.confdialer
#com.qualcomm.qti.devicestatisticsservice
#com.qualcomm.qti.dynamicddsservice
#com.qualcomm.qti.gpudrivers.sun.api35
#com.qualcomm.qti.ims
#com.qualcomm.qti.poweroffalarm
#com.qualcomm.qti.qcolor
#com.qualcomm.qti.qms.service.connectionsecurity
#com.qualcomm.qti.qms.service.trustzoneaccess
#com.qualcomm.qti.remoteSimlockAuth
#com.qualcomm.qti.ridemodeaudio
#com.qualcomm.qti.server.qtiwifi
#com.qualcomm.qti.server.wigig.tethering.rro
#com.qualcomm.qti.services.systemhelper
#com.qualcomm.qti.simcontacts
#com.qualcomm.qti.telephonyservice
#com.qualcomm.qti.uceShimService
#com.qualcomm.qti.uim
#com.qualcomm.qti.uimGbaApp
#com.qualcomm.qti.workloadclassifier
#com.qualcomm.qti.xrcb
#com.qualcomm.qti.xrvd.service
#com.qualcomm.timeservice
#com.qualcomm.uimremoteclient
#com.qualcomm.uimremoteserver
#com.qualcomm.wfd.service

#com.rongcard.eid
#com.tencent.soter.soterserver
#com.wapi.wapicertmanage

# 小米账号
com.xiaomi.account
# AI字幕
com.xiaomi.aiasst.vision
# 小米澎湃AI引擎
#com.xiaomi.aicr
#com.xiaomi.aon
#com.xiaomi.barrage
#com.xiaomi.bluetooth
#com.xiaomi.bluetooth.rro.device.config.overlay
#com.xiaomi.cameramind
#com.xiaomi.cameratools
#com.xiaomi.finddevice
#com.xiaomi.gnss.polaris
#com.xiaomi.joyose
#com.xiaomi.macro
#com.xiaomi.mi_connect_service
#com.xiaomi.micloud.sdk
#com.xiaomi.mirror
#com.xiaomi.misettings
#com.xiaomi.mtb
#com.xiaomi.otrpbroker
# 米币支付
com.xiaomi.payment
#com.xiaomi.phone
#com.xiaomi.phone.overlay
#com.xiaomi.registration
# 扫一扫
com.xiaomi.scanner
#com.xiaomi.simactivate.service
#com.xiaomi.touchservice
#com.xiaomi.trustservice
#com.xiaomi.ugd
#com.xiaomi.xmsf
#com.xiaomi.xmsfkeeper
#eu.xiaomi.ext
#miui.systemui.plugin
#org.codeaurora.ims
#org.ifaa.aidl.manager
#vendor.qti.bluetooth.xpan
#vendor.qti.bluetooth.xpan.overlay.target
#vendor.qti.data.txpwradmin
#vendor.qti.hardware.cacert.server
#vendor.qti.imsdatachannel
#vendor.qti.imsrcs
#vendor.qti.iwlan
#vendor.qti.qesdk.sysservice
